/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const DonorPublicView = IDL.Record({
  'id' : IDL.Text,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'bloodType' : IDL.Text,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'distanceKm' : IDL.Float64,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const MedicalShop = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'website' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addShop' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [Result],
      [],
    ),
  'checkAndUpdateAvailability' : IDL.Func([], [], []),
  'getAllDonors' : IDL.Func([], [IDL.Vec(DonorPublicView)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(DonorPublicView)], ['query']),
  'getShops' : IDL.Func([], [IDL.Vec(MedicalShop)], ['query']),
  'logDonation' : IDL.Func([], [Result], []),
  'registerDonor' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [Result],
      [],
    ),
  'searchDonors' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64],
      [IDL.Vec(DonorPublicView)],
      [],
    ),
  'updateDonorProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const DonorPublicView = IDL.Record({
    'id' : IDL.Text,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'bloodType' : IDL.Text,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'distanceKm' : IDL.Float64,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const MedicalShop = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'website' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addShop' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [Result],
        [],
      ),
    'checkAndUpdateAvailability' : IDL.Func([], [], []),
    'getAllDonors' : IDL.Func([], [IDL.Vec(DonorPublicView)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(DonorPublicView)], ['query']),
    'getShops' : IDL.Func([], [IDL.Vec(MedicalShop)], ['query']),
    'logDonation' : IDL.Func([], [Result], []),
    'registerDonor' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [Result],
        [],
      ),
    'searchDonors' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64],
        [IDL.Vec(DonorPublicView)],
        [],
      ),
    'updateDonorProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };