/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DonorPublicView {
  'id' : string,
  'lat' : number,
  'lng' : number,
  'bloodType' : string,
  'name' : string,
  'isAvailable' : boolean,
  'distanceKm' : number,
  'address' : string,
  'phone' : string,
}
export interface MedicalShop {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'website' : [] | [string],
  'address' : string,
  'phone' : string,
}
export type Result = { 'ok' : null } |
  { 'err' : string };
export interface _SERVICE {
  'addShop' : ActorMethod<
    [string, string, string, [] | [string], string],
    Result
  >,
  'checkAndUpdateAvailability' : ActorMethod<[], undefined>,
  'getAllDonors' : ActorMethod<[], Array<DonorPublicView>>,
  'getMyProfile' : ActorMethod<[], [] | [DonorPublicView]>,
  'getShops' : ActorMethod<[], Array<MedicalShop>>,
  'logDonation' : ActorMethod<[], Result>,
  'registerDonor' : ActorMethod<
    [string, string, string, string, number, number],
    Result
  >,
  'searchDonors' : ActorMethod<
    [string, number, number],
    Array<DonorPublicView>
  >,
  'updateDonorProfile' : ActorMethod<
    [string, string, string, number, number],
    Result
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];